name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_BASE_ID: ${{ secrets.BASE_ID }}
      EXPO_PUBLIC_BASE_APIKEY: ${{ secrets.BASE_APIKEY }}
      CONFIGURED: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.4
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 6.0.6
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: yarn install
      - run: expo publish
